### ISSUE TITLE
df_status without variable display

### ISSUE THREAD

**Issue by sandozGithub** [pablo14/funModeling#11]
Hi,
using
library("funModeling", lib.loc="~/R/win-library/3.5"),
df_status(datin) displays :
 >df_status(datin)
   variable q_zeros p_zeros   q_na   p_na q_inf p_inf      type unique
1         1       0    0.00      0   0.00     0     0   numeric  10175
2         2       0    0.00      0   0.00     0     0   numeric     20
3         3       0    0.00      0   0.00     0     0 character      2
..........
..........
several weeks ago, when I started using this library, I had the variable in the display.
what's wrong?

sandoz@free.fr

**Comment by pablo14** [comment]
Hi Sandoz!

That's strange... Anything has changed in df_status, can you add a sample
with 10 rows of datin so I can replicate the error?

Thanks!

**Comment by sandozGithub** [comment]
Hi, 
I re installed R & RStudio this morning , and could have df_status working correctly again... 
the person who coded this function could have an idea of why the variable did not show up... 

May I have a question about data preparation ? 
on the site 
[ https://www.hackerearth.com/blog/machine-learning/beginners-tutorial-on-xgboost-parameter-tuning-r/ | https://www.hackerearth.com/blog/machine-learning/beginners-tutorial-on-xgboost-parameter-tuning-r/ ] 

we can see that missing values are filled with "Missing" 


#set all missing value as "Missing" 
> train[is.na(train)] <- "Missing" 
> test[is.na(test)] <- "Missing" 




Is it a good idea? 





if it's a numeric value, the whole column is turned into categorical values and when comes 


the hot encoding through the matrix operation (for XGBoost for example), 


every continuous value generates a new column of categorical value. 

I was not aware of this and it took me sometime to find why my model was wrong... 




De: "Pablo Casas" <notifications@github.com> 
À: "pablo14/funModeling" <funModeling@noreply.github.com> 
Cc: "sandoz" <sandoz@free.fr>, "Author" <author@noreply.github.com> 
Envoyé: Mercredi 12 Décembre 2018 02:48:02 
Objet: Re: [pablo14/funModeling] df_status without variable display (#11) 

Hi Sandoz! 

That's strange... Anything has changed in df_status, can you add a sample 
with 10 rows of datin so I can replicate the error? 

Thanks!

**Comment by pablo14** [comment]
Hi!
I code the function, and did a [check](https://github.com/pablo14/funModeling/commit/61e331e2d3eebe003dd17d4772b7fe80b9bef592) on how long it's been unchanged, (more than a year). So the problem should have been in another place.

If you find the error again, take a sample and send it here so I can reproduce it.

Regarding the data preparation question. The short answer is: "yes, with care". It's not a good idea to put the "missing" in a numerical variable with +10 unique values. It is needed to transform into categorical with some discretization criteria, or, put the missing with some value (you should be careful about inserting non-real bias into the model)....

I suggest you read the following chapters from the Data Science Live Book:

[Treating missing values in numerical variables](https://livebook.datascienceheroes.com/data-preparation.html#treating-missing-values-in-numerical-variables)

[High Cardinality Variable in Predictive Modeling](https://livebook.datascienceheroes.com/data-preparation.html#high_cardinality_predictive_modeling)

~ Cheers
