### ISSUE TITLE
warnings

### ISSUE THREAD

**Issue by VladPerervenko** [pablo14/funModeling#16]
` _plotar(data=heart_disease, target="has_heart_disease", plot_type="histdens")_
**Warnings:**
1: `group_by_()` is deprecated as of dplyr 0.7.0. Please use `group_by()` instead.
See vignette('programming') for more help. This warning is displayed once every 8 hours.
Call `lifecycle::last_warnings()` to see where this warning was generated. 
2: `summarise_()` is deprecated as of dplyr 0.7.0.
Please use `summarise()` instead.
This warning is displayed once every 8 hours.
Call `lifecycle::last_warnings()` to see where this warning was generated. 
3: Removed 4 rows containing non-finite values (stat_density). 
 _plotar(heart_disease, input = 'age', target = 'chest_pain', plot_type = "boxplot")_
**Warning**:
`fun.y` is deprecated. Use `fun` instead.`

**Comment by pablo14** [comment]
Thanks! Yes I could see the error, I will release the fix soon.

**Comment by sfd99** [comment]
**_Hi Pablo,_** 
funModeling is _truly_ a great, useful pkg!.

**_Q:_**
library(funModeling)
library(tidyverse)
library(Hmisc)

Run all the functions in this post in one-shot, 
with the following function:

    basic_eda <- function(data)
    {
        glimpse(data)
        df_status(data)
        freq(data)
        profiling_num(data)
        plot_num(data)
        describe(data)
    }

OK! I then run in the Rstudio Console: 
**basic_eda(iris)**
and all lines in **basic_eda** work fine,
_EXCEPT for_:
**profiling_num(data)**

No output at all from the line: 
**profiling_num(data)**
in basic_eda!.

If I run:
**profiling_num(iris)**
individually, (ie: _OUTSIDE_ the function **basic_eda**),
_all by itself,_ in Rstudio Console panel,
it runs fine. 100%!

But _INSIDE_ the function **basic_eda**,
along with other funModeling pkg. functions,
it does not seem to run at all.

It does run by itself, 
(ie: if it's _the only line in **basic_eda**).
Weird...Check it out...

Help Pablo!.
What am I missing?...

**R 3.6.3 (latest)
Rstudio version 1.2.5033 (latest)
Ubuntu Linux 18.04 64bits.**

**Comment by pablo14** [comment]
Hi @sfd99 ! Thanks for reporting you are right, I changed the default print behavior, the fix is quite esay and all you have to do is to add the print():

basic_eda <- function(data)
{
    glimpse(data)
    df_status(data)
    freq(data)
    **print(profiling_num(data))** #here
    plot_num(data)
    describe(data)
}

**Comment by sfd99** [comment]
Thanks, Pablo.
With print() it works!.

_Out of curiosity..._
why is the pkg function: 
profiling_num(data)
_the only one_ 
that needs to have **print()** appended
to output the results in basic_eda()?.
None of the other fun functions need it... :-)

**Comment by pablo14** [comment]
Hmm I just realized that `status`  also needs a print. You were using
`df_status` right? This function is previous to status and it does not have
a print inside the function.

Same goes for `profiling_num`, in a very first place it has a print before
the return, and it causes undesirable print in the console.

You can check the magic inside the functions, just print the name of each
one, write them without the `(..)`  ;)

**Comment by sfd99** [comment]
Hi Pablo,

Nope,
   **df_status(data)**
outputs results just fine,
from inside the function: 
**basic_eda (iris)**.

In other words,
no print() around it is necessary...
Works fine!.

It's just:
**profiling_num(data)**
that seems to need a print() before it,
inside the Fx :
**basic_eda(iris)**...

**Comment by pablo14** [comment]
Hi! df_status() is old, not deprecated but I encourage you to use *status()
*it does not print by default.
Cheers!

**Comment by sfd99** [comment]
_Thanks, Pablo._
Will try.
Have a nice and safe weekend in Buenos Aires.

**Comment by pablo14** [comment]
Hi!
closing due to df_status is deprecated

**Comment by sfd99** [comment]
**_Pablo,_**

What is the latest version
of the great funModeling PKG,
and what's the best source to D/L ? 
from CRAN? GIThub?.

My current version is: 1.9.4

Thanks!!
**SFd**

**Comment by pablo14** [comment]
CRAN it's ok
