### ISSUE TITLE
No output from profiling_num(data) inside fx basic_eda(iris)

### ISSUE THREAD

**Issue by sfd99** [pablo14/funModeling#17]
**_Hi Pablo,_**

funModelling is a great, useful pkg.
Thanks!.

**_Q:_**
the post example R code shows:

"Run all the functions in this post in one-shot, 
with the following function:"
    
    basic_eda <- function(data)
    {
        glimpse(data)
        df_status(data)
        freq(data)
        profiling_num(data)
        plot_num(data)
        describe(data)
    }

but running: 
basic_eda(iris)
does not show the output results of: 
**profiling_num(data)**

All other lines in basic_eda(iris)
run fine, 
**_except profiling_num_**.

Running  basic_eda(iris)
with ONLY 1 line (by itself):
**profiling_num(iris)**
runs fine...

Also, running 
**profiling_num(data)**
from the Rstudio Console,
works fine,

_Help Pablo!_
_using:_
**funModeling pkg 1.9.4
R 3.6.3
Rstudio 1.2.5033 (latest)
Ubuntu Linux 18.04**

**Comment by pablo14** [comment]
Hi! replied in https://github.com/pablo14/funModeling/issues/16 
Thanks :D
