### ISSUE TITLE
plot_num returning error

### ISSUE THREAD

**Issue by ZellW** [pablo14/funModeling#8]
Oddly, plot_num has been throwing this error:

Error: `predicate` must be a closure or function pointer.

I can repeat it with common datasets like iris or cars.  Any ideas?

**Comment by pablo14** [comment]
Hi! It's working on my machine (`plot_num(iris)`), what is your R and `funModeling` version? The latest one is 1.6.7.

**Comment by ZellW** [comment]
This is strange.  Restarted RStudio, loaded only funModeling - same error.

R version 3.4.1 (2017-06-30)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] funModeling_1.6.7  Hmisc_4.1-1        ggplot2_2.2.1.9000 Formula_1.2-2      survival_2.41-3    lattice_0.20-35

**Comment by ZellW** [comment]
I upgraded to R 3.44.  Started a new session, same error - the other funModeling functions work fine.
Error rises in R GUI and RStudio.

Error: `predicate` must be a closure or function pointer
Called from: rlang::flatten_if(facets_list, is.list)

**Comment by pablo14** [comment]
Please show me the complete script you are running. Dplyr version?

**Comment by ZellW** [comment]
I rebooted my PC, opened RStudio and then:

library(funModeling)
plot_num(iris)

and got the recurring error:

 Error: `predicate` must be a closure or function pointer 

dplyr version 0.7.4

**Comment by ZellW** [comment]
I am beginning to believe this is a ggplot issue. . . .

**Comment by ZellW** [comment]
While I do not have this resolved, the problem is likely here:  https://github.com/tidyverse/ggplot2/issues/2497

**Comment by ZellW** [comment]
Reinstalling ggplot2 2.2.1 (NOT 2.2.1.9000) solved the facet_wrap issue and plot_num works.

**Comment by pablo14** [comment]
Cool - Thanks for the update Cliff!
