### ISSUE TITLE
correlation_table not running for only numeric variables

### ISSUE THREAD

**Issue by tsimard111** [pablo14/funModeling#9]
It seems like the correlation_table function is not skipping categorical variables. When I run it against a table with a mix of numeric and categorical variables I get the error "Error in cor(data, use = "complete.obs") : 'x' must be numeric". When I manually subset to the numeric variables I have no problem.

**Comment by pablo14** [comment]
Hi, thanks for reporting. It works for me. What funModeling version are you running? Latest is 1.6.7.

The code I run was:

```
library(funModeling)
# this dataframe contains factor, int and num variables, I also tried with character.
correlation_table(heart_disease, "has_heart_disease")
```

**Comment by pablo14** [comment]
Open if the problem persists.
